# -*- coding: utf-8 -*-
"""Pytest entry points for the YAML validation suite.

Run with::

    pytest tests/cases/yaml/test_yaml_cases.py

Each entry in :data:`tests.cases.yaml.catalog.YAML_CASES` becomes a
parametrized test that integrates the M4E model and asserts a per-body
NRMSE tolerance against the PyChrono reference. The truth files live under
``Validation2externalSoft/results/yaml_*/`` and are never modified or
regenerated by the test — only the cached ``*_chrono.npy`` (or
``trajectory.csv`` as a fallback) are read.

Tolerances are intentionally loose enough to absorb integrator-method drift
across SciPy versions but tight enough to flag a regression in the symbolic
EOM or the YAML parser.
"""
from __future__ import annotations

import pytest

from .catalog import YAML_CASES, YamlCaseEntry
from .runner import compare_against_chrono


# Per-case NRMSE tolerances. Tuned from current passing values
# (worst case observed: ~3.3e-5 for position, ~2.3e-5 for velocity).
POSITION_NRMSE_TOL = 1.0e-4
VELOCITY_NRMSE_TOL = 1.0e-3


@pytest.mark.parametrize(
    "case",
    YAML_CASES,
    ids=lambda c: c.case_id if isinstance(c, YamlCaseEntry) else str(c),
)
def test_yaml_matches_chrono(case: YamlCaseEntry) -> None:
    result = compare_against_chrono(case)

    pos_nrmse = result["position_metrics"]["NRMSE_per_body"]
    vel_nrmse = result["velocity_metrics"]["NRMSE_per_body"]

    pos_max = float(pos_nrmse.max())
    vel_max = float(vel_nrmse.max())

    assert pos_max < POSITION_NRMSE_TOL, (
        f"{case.case_id}: max position NRMSE {pos_max:.3e} exceeds "
        f"tolerance {POSITION_NRMSE_TOL:.1e}. Per-body: {pos_nrmse.tolist()}"
    )
    assert vel_max < VELOCITY_NRMSE_TOL, (
        f"{case.case_id}: max velocity NRMSE {vel_max:.3e} exceeds "
        f"tolerance {VELOCITY_NRMSE_TOL:.1e}. Per-body: {vel_nrmse.tolist()}"
    )
