# source/multibody/flexible/flex_file_writer.py
"""
@author: Sahand Sabet

File-generation layer (tasks 11-12) for the FSM-in-core preprocessor.

Formats the plain-data output of expand_flex_table() as a readable,
standalone .py file in exactly the same flat-list convention every
hand-written script in Examples_mbd/ already uses (confirmed directly
against _1_Double_pendulum.py and MbdSystem.from_example()'s expected
attributes). This is a pure formatting layer -- it never re-derives any of
the design's actual logic (merge rules, stiffness formulas, mass-merge,
etc.), only renders an already-computed result as source text.
"""
import os
import math
import numpy as np

from .flex_expand import expand_flex_table

_MARKER = "# ===================== USER ADDITIONS BELOW ====================="


def _fmt(value):
    """
    Render a plain Python/NumPy value as valid Python source text.
    Recurses into lists/tuples/dicts, since a NaN float's own repr() is the
    literal text "nan" -- not valid Python syntax on its own -- and this
    would otherwise only get caught at the TOP level, not inside a nested
    list (prismatic_direction is exactly this: a list of [nan, nan] pairs).
    """
    if isinstance(value, np.ndarray):
        return _fmt(value.tolist())
    if isinstance(value, np.generic):
        return _fmt(value.item())  # numpy scalar (e.g. np.float64) -> plain Python type
    if isinstance(value, float) and math.isnan(value):
        return "float('nan')"
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_fmt(v) for v in value)
        if isinstance(value, tuple):
            return f"({inner}{',' if len(value) == 1 else ''})"
        return f"[{inner}]"
    if isinstance(value, dict):
        inner = ", ".join(f"{_fmt(k)}: {_fmt(v)}" for k, v in value.items())
        return f"{{{inner}}}"
    return repr(value)


def _format_as_source(expanded, ic, gVec, g, tspan, TimeStep,
                       animation_on, SaveMovieOn, plotTstep, integrator_kwargs,
                       table1, table2):
    joints = expanded["joints"]
    n_bodies = len(joints)

    lines = [
        '# -*- coding: utf-8 -*-',
        '"""',
        "Auto-generated by multibody.generate_flex_model_file().",
        "",
        f'Do not hand-edit above the "{_MARKER.strip("# ")}" marker below --',
        "re-running the generator will overwrite everything above it.",
        '"""',
        "import sys",
        "import os",
        "",
        "source_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))",
        "sys.path.insert(0, source_dir)",
        "",
        "import numpy as np",
        "import sympy as sym",
        "",
        "import multibody as mb",
        "from multibody import JointSystem, normalize_prismatic",
        "from multibody import symvars_definition",
        "",
        "Reference_frame_Origin = np.array([0, 0])",
        "",
        f"joints = {_fmt(joints)}",
        f"types = {_fmt(expanded['types'])}",
        f"parent_cg_to_joint = {_fmt(expanded['parent_cg_to_joint'])}",
        f"joint_to_child_cg = {_fmt(expanded['joint_to_child_cg'])}",
        f"prismatic_direction = {_fmt(expanded['prismatic_direction'])}",
        "prismatic_direction = normalize_prismatic(prismatic_direction)",
        "",
        "Initial_Points = {}",
        "# Ground points: fixed [x, z] coordinates.",
        f"Initial_Points[\"GR\"] = {_fmt(expanded['Initial_Points']['GR'])}",
        "# Body-defined points (\"BD\"): dictionary keyed by real body number.",
        f"Initial_Points[\"BD\"] = {_fmt(expanded['Initial_Points']['BD'])}",
        "",
        "# No symbolic force/body-data parameters used by the auto-generated",
        "# FSM springs -- extend these two lists (and ForcesPointsNum/BodyDataNum",
        "# below) if you add your own symbolic forces past the marker.",
        "ForcesPointsSym = []",
        "BodyDataSym = []",
        "",
        "Force = {}",
        "# Forces applied on body-defined points (PointsBD):",
        f"Force[\"PointsBD\"] = {_fmt(expanded['Force']['PointsBD'])}",
        "# Forces applied at the center of gravity (CG):",
        f"Force[\"CG\"] = {_fmt(expanded['Force']['CG'])}",
        "# Tension springs: list of tuples (connection, [l0, stiffness]).",
        f"Force[\"TensionSpring\"] = {_fmt(expanded['Force']['TensionSpring'])}",
        "# Tension dampers:",
        f"Force[\"TensionDamper\"] = {_fmt(expanded['Force']['TensionDamper'])}",
        "# Torsion springs: list of tuples ([body1, body2], [theta_0, k]) --",
        "# includes the auto-generated FSM bending springs for every flexible member.",
        f"Force[\"TorsionSpring\"] = {_fmt(expanded['Force']['TorsionSpring'])}",
        "# Torsion dampers:",
        f"Force[\"TorsionDamper\"] = {_fmt(expanded['Force']['TorsionDamper'])}",
        "",
        f"ic = np.array({_fmt(list(ic))})",
        f"m0 = np.array({_fmt(list(expanded['m0']))})",
        f"J0 = np.array({_fmt(list(expanded['J0']))})",
        f"gVec = np.array({_fmt(list(gVec))}).reshape(-1, 1)",
        f"g = {g!r}",
        "",
        "ForcesPointsNum = np.ones(len(ForcesPointsSym))",
        "BodyDataNum = np.ones(len(BodyDataSym))",
        "",
        f"tspan = {tspan!r}",
        f"TimeStep = {TimeStep!r}",
        "",
        f"animation_on = {animation_on!r}  # Display animation: 1, 0-otherwise",
        f"SaveMovieOn = {SaveMovieOn!r}  # Extension e.g. '.gif' saves the animation, otherwise None",
        f"plotTstep = {plotTstep!r}  # how many times faster are we plotting w.r.t. simulation time",
        "",
        "# FSM's bending springs make this system stiff -- the default explicit",
        "# RK45 solver can hang. main.py reads this (falls back to {} / plain RK45",
        "# if absent, so ordinary rigid examples are unaffected).",
        f"integrator_kwargs = {_fmt(integrator_kwargs)}",
        "",
        "#%% Checks section: ensures everything is defined correctly",
        "mb.checks.bodies(joints, types, parent_cg_to_joint, joint_to_child_cg, prismatic_direction)",
        "mb.checks.points_forces(joints, types, Initial_Points, Force)",
        "",
        f"NBodies = {n_bodies}  # for reference: real body numbers run 1.." + str(n_bodies),
        "",
        "# Original (pre-expansion) Table 1 / Table 2 -- kept ONLY so main.py can",
        "# print all 3 tables (Table 1, Table 2, and the expanded Table 3 above).",
        "# NOT used by MbdSystem/expand_flex_table -- the expanded lists above are",
        "# the ones actually consumed.",
        f"flex_table1 = {_fmt(table1)}",
        f"flex_table2 = {_fmt(table2)}",
        "",
        _MARKER,
        "# Add any additional Force entries here, using the real body numbers",
        "# above (e.g. Force['PointsBD'].append([<real_body>, 0, Fx, Fz, My])).",
        "# Bodies belonging to a flexible member can ONLY be referenced here,",
        "# never in the pre-expansion input Table 1/Table 2 call.",
        "",
    ]
    return "\n".join(lines) + "\n"


def generate_flex_model_file(joints, types, parent_cg_to_joint, joint_to_child_cg,
                              prismatic_direction, flex_bd, m0, J0,
                              flex_bds, flex_n_seg, flex_L, flex_E, flex_A, flex_I, flex_rho,
                              flex_deformation_mode, flex_clamp_on, output_path, *,
                              flex_m=None, flex_J=None, Force=None, Initial_Points=None,
                              ic=None, gVec=None, g=9.81, tspan=5.0, TimeStep=0.05,
                              animation_on=1, SaveMovieOn=None, plotTstep=5,
                              integrator_kwargs=None,
                              overwrite=False):
    """
    Task 12: the one public entry point. Expands Table 1 + Table 2 (calling
    expand_flex_table internally) and writes a complete, standalone .py file
    in the same flat-list convention every hand-written example already uses.

    Parameters
    ----------
    joints, types, parent_cg_to_joint, joint_to_child_cg, prismatic_direction, m0, J0 :
        The SAME parallel lists any rigid-case script already defines, plus
        flex_bd (see flex_expand module docstring).
    flex_bd : list[int or nan/None]
        nan/None for a rigid row; for a flexible row, MUST equal that row's
        own (1-based) body index -- e.g. row 4 is flexible -> flex_bd[3] = 4.
    flex_n_seg, flex_L, flex_E, flex_A, flex_I, flex_rho, flex_deformation_mode,
    flex_clamp_on, flex_m, flex_J :
        Table 2's parallel lists, indexed by POSITION (flex_bds gives each
        position's real body index).
    flex_bds : list[int]
        The actual (1-based) body index of each Table 2 row, e.g. [2, 4].
        Cross-validated against Table 1's flex_bd -- every flexible row in
        Table 1 must appear here exactly once, and vice versa.
    output_path : str
        Path to write the generated .py file to.
    Force, Initial_Points : optional dict
        Ordinary (non-flexible-body) forces/points, written EXACTLY like
        today's convention -- any reference to a flexible body is rejected
        (see expand_flex_table/_validate_no_flex_forces).
    ic : optional array-like
        Initial conditions (length 2*n_bodies: positions then velocities).
        Defaults to all zeros.
    gVec : optional array-like
        Per-body gravity scale (length n_bodies). Defaults to all ones.
    animation_on, SaveMovieOn, plotTstep :
        Written into the generated file exactly like any hand-written
        example (see e.g. _1_Double_pendulum.py) -- control mb.plot.animate_multibody
        usage in the generated file/your own driver script.
    integrator_kwargs : optional dict
        Extra keyword args passed to MbdSystem.integrate() by main.py (via
        getattr(ex, 'integrator_kwargs', {})). Defaults to
        {'algorithm': 'Radau', 'rtol': 1e-4, 'atol': 1e-6} -- FSM's bending
        springs make the default explicit RK45 solver hang.
    overwrite : bool
        If False (default) and output_path already exists, raises rather
        than silently overwriting a possibly hand-edited file.
    """
    if integrator_kwargs is None:
        integrator_kwargs = {"algorithm": "Radau", "rtol": 1e-4, "atol": 1e-6}
    expanded = expand_flex_table(joints, types, parent_cg_to_joint, joint_to_child_cg,
                                  prismatic_direction, flex_bd, m0, J0,
                                  flex_bds, flex_n_seg, flex_L, flex_E, flex_A, flex_I, flex_rho,
                                  flex_deformation_mode, flex_clamp_on,
                                  flex_m=flex_m, flex_J=flex_J,
                                  Force=Force, Initial_Points=Initial_Points, ic=ic)
    n_bodies = len(expanded["types"])
    n_total_dof = expanded["n_total_dof"]

    if ic is None:
        ic = np.zeros(2 * n_total_dof)
    if gVec is None:
        gVec = np.ones(n_bodies)

    table1 = {
        "joints": joints, "types": types,
        "parent_cg_to_joint": parent_cg_to_joint, "joint_to_child_cg": joint_to_child_cg,
        "prismatic_direction": prismatic_direction, "m0": m0, "J0": J0, "flex_bd": flex_bd,
    }
    table2 = {
        "flex_bds": flex_bds, "flex_n_seg": flex_n_seg, "flex_L": flex_L,
        "flex_E": flex_E, "flex_A": flex_A, "flex_I": flex_I, "flex_rho": flex_rho,
        "flex_deformation_mode": flex_deformation_mode, "flex_clamp_on": flex_clamp_on,
        "flex_m": flex_m, "flex_J": flex_J,
    }

    if os.path.exists(output_path) and not overwrite:
        raise FileExistsError(
            f"{output_path!r} already exists -- pass overwrite=True to "
            f"replace it (any hand-edits past the USER ADDITIONS marker "
            f"will be lost)."
        )

    source = _format_as_source(expanded, ic, gVec, g, tspan, TimeStep,
                                animation_on, SaveMovieOn, plotTstep, integrator_kwargs,
                                table1, table2)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(source)

    return output_path

