# -*- coding: utf-8 -*-
"""
Auto-generated by multibody.generate_flex_model_file().

Do not hand-edit above the "===================== USER ADDITIONS BELOW =====================" marker below --
re-running the generator will overwrite everything above it.
"""
import sys
import os

source_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, source_dir)

import numpy as np
import sympy as sym

import multibody as mb
from multibody import JointSystem, normalize_prismatic
from multibody import symvars_definition

Reference_frame_Origin = np.array([0, 0])

joints = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11]]
types = ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
parent_cg_to_joint = [[0.0, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0]]
joint_to_child_cg = [[0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.075, 0.0], [0.0, 0.0]]
prismatic_direction = [[float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')], [float('nan'), float('nan')]]
prismatic_direction = normalize_prismatic(prismatic_direction)

Initial_Points = {}
# Ground points: fixed [x, z] coordinates.
Initial_Points["GR"] = []
# Body-defined points ("BD"): dictionary keyed by real body number.
Initial_Points["BD"] = {}

# No symbolic force/body-data parameters used by the auto-generated
# FSM springs -- extend these two lists (and ForcesPointsNum/BodyDataNum
# below) if you add your own symbolic forces past the marker.
ForcesPointsSym = []
BodyDataSym = []

Force = {}
# Forces applied on body-defined points (PointsBD):
Force["PointsBD"] = []
# Forces applied at the center of gravity (CG):
Force["CG"] = []
# Tension springs: list of tuples (connection, [l0, stiffness]).
Force["TensionSpring"] = []
# Tension dampers:
Force["TensionDamper"] = []
# Torsion springs: list of tuples ([body1, body2], [theta_0, k]) --
# includes the auto-generated FSM bending springs for every flexible member.
Force["TorsionSpring"] = [([0, 1], [0.005, 32152.0]), ([1, 2], [0.0, 16076.0]), ([2, 3], [0.0, 16076.0]), ([3, 4], [0.0, 16076.0]), ([4, 5], [0.0, 16076.0]), ([5, 6], [0.0, 16076.0]), ([6, 7], [0.0, 16076.0]), ([7, 8], [0.0, 16076.0]), ([8, 9], [0.0, 16076.0]), ([9, 10], [0.0, 16076.0])]
# Torsion dampers:
Force["TorsionDamper"] = []

ic = np.array([0.005, 0.010000000000000002, 0.015000000000000003, 0.020000000000000004, 0.025000000000000005, 0.030000000000000006, 0.035, 0.04, 0.045000000000000005, 0.05, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
m0 = np.array([0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 0.111375, 2.0])
J0 = np.array([0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.000208828125, 0.00032])
gVec = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]).reshape(-1, 1)
g = 9.81

ForcesPointsNum = np.ones(len(ForcesPointsSym))
BodyDataNum = np.ones(len(BodyDataSym))

tspan = 0.2
TimeStep = 0.002

animation_on = 1  # Display animation: 1, 0-otherwise
SaveMovieOn = None  # Extension e.g. '.gif' saves the animation, otherwise None
plotTstep = 5  # how many times faster are we plotting w.r.t. simulation time

# FSM's bending springs make this system stiff -- the default explicit
# RK45 solver can hang. main.py reads this (falls back to {} / plain RK45
# if absent, so ordinary rigid examples are unaffected).
integrator_kwargs = {'algorithm': 'Radau', 'rtol': 0.0001, 'atol': 1e-06}

#%% Checks section: ensures everything is defined correctly
mb.checks.bodies(joints, types, parent_cg_to_joint, joint_to_child_cg, prismatic_direction)
mb.checks.points_forces(joints, types, Initial_Points, Force)

NBodies = 11  # for reference: real body numbers run 1..11

# Original (pre-expansion) Table 1 / Table 2 -- kept ONLY so main.py can
# print all 3 tables (Table 1, Table 2, and the expanded Table 3 above).
# NOT used by MbdSystem/expand_flex_table -- the expanded lists above are
# the ones actually consumed.
flex_table1 = {'joints': [[0, 1], [1, 2]], 'types': ['R', 'R'], 'parent_cg_to_joint': [[0.0, 0.0], [0.75, 0.0]], 'joint_to_child_cg': [[0.75, 0.0], [0.0, 0.0]], 'prismatic_direction': [[float('nan'), float('nan')], [float('nan'), float('nan')]], 'm0': [None, 2.0], 'J0': [None, 0.00032], 'flex_bd': [1, float('nan')]}
flex_table2 = {'flex_bds': [1], 'flex_n_seg': [10], 'flex_L': [1.5], 'flex_E': [2411.4], 'flex_A': [1.0], 'flex_I': [1.0], 'flex_rho': [0.7425], 'flex_deformation_mode': ['bending'], 'flex_clamp_on': [True], 'flex_m': None, 'flex_J': None}

# ===================== USER ADDITIONS BELOW =====================
# Add any additional Force entries here, using the real body numbers
# above (e.g. Force['PointsBD'].append([<real_body>, 0, Fx, Fz, My])).
# Bodies belonging to a flexible member can ONLY be referenced here,
# never in the pre-expansion input Table 1/Table 2 call.

