# -*- coding: utf-8 -*-
"""
Auto-generated by multibody.generate_flex_model_file().

Do not hand-edit above the "===================== USER ADDITIONS BELOW =====================" marker below --
re-running the generator will overwrite everything above it.
"""
import sys
import os

source_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, source_dir)

import numpy as np
import sympy as sym

import multibody as mb
from multibody import JointSystem, normalize_prismatic
from multibody import symvars_definition

Reference_frame_Origin = np.array([0, 0])

joints = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9]]
types = ['F', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P']
parent_cg_to_joint = [[0.0, 0.0], [0.0, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.0, 0.0]]
joint_to_child_cg = [[float('nan'), float('nan')], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.08333333333333333, 0.0], [0.0, 0.0], [0.0, 0.0]]
prismatic_direction = [[float('nan'), float('nan')], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]
prismatic_direction = normalize_prismatic(prismatic_direction)

Initial_Points = {}
# Ground points: fixed [x, z] coordinates.
Initial_Points["GR"] = []
# Body-defined points ("BD"): dictionary keyed by real body number.
Initial_Points["BD"] = {}

# No symbolic force/body-data parameters used by the auto-generated
# FSM springs -- extend these two lists (and ForcesPointsNum/BodyDataNum
# below) if you add your own symbolic forces past the marker.
ForcesPointsSym = []
BodyDataSym = []

Force = {}
# Forces applied on body-defined points (PointsBD):
Force["PointsBD"] = []
# Forces applied at the center of gravity (CG):
Force["CG"] = []
# Tension springs: list of tuples (connection, [l0, stiffness]).
Force["TensionSpring"] = [(('CG1_1', 'CG2_2'), [0.08333333333333333, 12000000.000000002]), (('CG2_2', 'CG3_3'), [0.16666666666666666, 6000000.000000001]), (('CG3_3', 'CG4_4'), [0.16666666666666666, 6000000.000000001]), (('CG4_4', 'CG5_5'), [0.16666666666666666, 6000000.000000001]), (('CG5_5', 'CG6_6'), [0.16666666666666666, 6000000.000000001]), (('CG6_6', 'CG7_7'), [0.16666666666666666, 6000000.000000001]), (('CG7_7', 'CG8_8'), [0.08333333333333333, 12000000.000000002])]
# Tension dampers:
Force["TensionDamper"] = []
# Torsion springs: list of tuples ([body1, body2], [theta_0, k]) --
# includes the auto-generated FSM bending springs for every flexible member.
Force["TorsionSpring"] = []
# Torsion dampers:
Force["TorsionDamper"] = []

ic = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
m0 = np.array([5.0, 1.6666666666666665e-07, 1.6666666666666665e-07, 1.6666666666666665e-07, 1.6666666666666665e-07, 1.6666666666666665e-07, 1.6666666666666665e-07, 1e-06, 2.0])
J0 = np.array([1.0, 3.858024691358024e-10, 3.858024691358024e-10, 3.858024691358024e-10, 3.858024691358024e-10, 3.858024691358024e-10, 3.858024691358024e-10, 1e-06, 1e-06])
gVec = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]).reshape(-1, 1)
g = 9.81

ForcesPointsNum = np.ones(len(ForcesPointsSym))
BodyDataNum = np.ones(len(BodyDataSym))

tspan = 1.0
TimeStep = 0.01

animation_on = 1  # Display animation: 1, 0-otherwise
SaveMovieOn = None  # Extension e.g. '.gif' saves the animation, otherwise None
plotTstep = 5  # how many times faster are we plotting w.r.t. simulation time

# FSM's bending springs make this system stiff -- the default explicit
# RK45 solver can hang. main.py reads this (falls back to {} / plain RK45
# if absent, so ordinary rigid examples are unaffected).
integrator_kwargs = {'algorithm': 'Radau', 'rtol': 0.0001, 'atol': 1e-06}

#%% Checks section: ensures everything is defined correctly
mb.checks.bodies(joints, types, parent_cg_to_joint, joint_to_child_cg, prismatic_direction)
mb.checks.points_forces(joints, types, Initial_Points, Force)

NBodies = 9  # for reference: real body numbers run 1..9

# ===================== USER ADDITIONS BELOW =====================
# Add any additional Force entries here, using the real body numbers
# above (e.g. Force['PointsBD'].append([<real_body>, 0, Fx, Fz, My])).
# Bodies belonging to a flexible member can ONLY be referenced here,
# never in the pre-expansion input Table 1/Table 2 call.

