import numpy as np
import sympy as sym
import warnings
from enum import Enum
from pandas import DataFrame, set_option
# from IPython.display import display

def normalize_prismatic(prismatic_direction):
    """
    Normalize a list of 2D prismatic‐axis vectors into unit‐length Sympy Matrices.

    For each vector in `prismatic_direction`, this function:
      1. Converts it to a `sympy.Matrix`.
      2. Checks that it contains no `nan` entries and that its Euclidean norm is non-zero.
      3. If valid, divides the vector by its norm to produce a unit‐length axis.
      4. Otherwise, returns `Matrix([nan, nan])` for that entry.

    Parameters
    ----------
    prismatic_direction : Sequence[Sequence[float or sympy.Expr]]
        Iterable of 2-element sequences specifying the local axis direction
        for each prismatic joint. Non‐prismatic or uninitialized joints
        should be passed as `[nan, nan]`.

    Returns
    -------
    List[sympy.Matrix]
        A list of 2×1 `sympy.Matrix` objects, each of unit length (for valid
        inputs) or `[nan, nan]` if the original vector was invalid or zero-length.
    """
    
    return [
        vec / sym.sqrt(vec.dot(vec)) if not vec.has(sym.nan) and sym.sqrt(vec.dot(vec)) != 0 else sym.Matrix([sym.nan, sym.nan])
        for vec in map(sym.Matrix, prismatic_direction)
    ]

# Define the supported joint types.
class JointType(Enum):
    REVOLUTE    = 'R'
    PRISMATIC   = 'P'
    FLOAT       = 'F'
    # (Other types such as SPHERICAL could be added if needed)

def normalize_vector(vec):
    """
    Normalizes a 2D vector.
    If all components are NaN, returns None.
    """
    vec = np.array(vec, dtype=float)
    # Check if the vector is undefined (all NaNs)
    if np.isnan(vec).all():
        return None
    norm = np.linalg.norm(vec)
    if norm == 0:
        warnings.warn("Zero-length vector cannot be normalized; returning original vector.")
        return vec
    return vec / norm

class Joint:
    def __init__(self, parent, child, joint_type, parent_cg_to_joint, joint_to_child_cg, prismatic_direction=None):
        """
        Manage a system of multibody joints.

        Parameters
        ----------
        parent : int
            Index of the parent body (0 = ground).
        child : int
            Index of the child body.
        joint_type : {'R','P','F'}
            Revolute, Prismatic or Floating joint.
        parent_cg_to_joint : array_like
            Vector from the parent’s CG to the joint.
        joint_to_child_cg : array_like
            Vector from the joint to the child’s CG.
        prismatic_direction : array_like, optional
            Unit vector for prismatic translation. Default is None.

        Returns
        -------
        None
        """
        self.parent             = parent
        self.child              = child
        self.joint_type         = JointType(joint_type)
        self.parent_cg_to_joint = sym.Matrix(parent_cg_to_joint)
        self.joint_to_child_cg  = sym.Matrix(joint_to_child_cg)
        
        # Store the prismatic direction as a numpy array.
        self.prismatic_direction = sym.Matrix(prismatic_direction) if prismatic_direction is not None else None

    def __repr__(self):
        return (f"Joint(parent={self.parent}, child={self.child}, type={self.joint_type.value}, "
                f"parent_cg_to_joint={self.parent_cg_to_joint.tolist()}, "
                f"joint_to_child_cg={self.joint_to_child_cg.tolist()}, "
                f"prismatic_direction={None if self.prismatic_direction is None else self.prismatic_direction.tolist()})")

class JointSystem:
    """
    Ordered collection of :class:`~multibody.Joint` objects plus
    convenience utilities for *symbolic* multibody modelling.

    A JointSystem stores every joint in the mechanism, keeps them
    sorted by their **child‐body index**, and exposes helper methods that
    bridge the gap between the tabular data a user typically writes and
    the richer objects required by the rest of the `multibody` package.

    Notes
    -----
    Ground is body 0. All other bodies are numbered consecutively
    starting at 1; joints are sorted so that the *k*-th entry in
    :attr:`joints` always corresponds to body *k*.

    All vectors are 2-D column vectors expressed in the global X-Z plane
    (right-handed with Y pointing *out* of the screen).

    Attributes
    ----------
    joints : list[:class:`~multibody.Joint`]
        List of Joint instances, sorted by child index.

    The following are generated by :meth:`coordinate_finder`:

    Q, QD, QDD : list[:class:`sympy.Symbol`]
        System-wide symbolic coordinates, velocities, and accelerations.

    NDOF : list[int]
        Degrees of freedom contributed by each joint (1 for ‘R’/’P’, 3 for ‘F’).

    Body_col : list[list[int]]
        Map from joint → global DOF index(es). Useful when assembling matrices.

    Examples
    --------
    >>> import sympy as sym
    >>> import numpy as np
    >>> from multibody import JointSystem, normalize_prismatic
    >>>
    >>> joints = [[0, 1], [1, 2]]
    >>> types  = ['F', 'R']
    >>> pcg2j  = [[0.0, 0.0], [1.5, 0.0]]
    >>> j2ccg  = [[np.nan, np.nan], [-1.0, 0.0]]
    >>> pris_d = normalize_prismatic([[np.nan, np.nan],
    ...                              [np.nan, np.nan]])
    >>>
    >>> sys = JointSystem.from_data(joints, types, pcg2j, j2ccg, pris_d)
    >>> sys.display_table()
    >>> Q, QD, QDD, NDOF, Body_col = sys.coordinate_finder()
    """

    def __init__(self):
        self.joints = []

    def add_joint(self, parent, child, joint_type, parent_cg_to_joint, joint_to_child_cg, prismatic_direction=None):
        """
        Create a Joint instance and add it to the system.
        """
        joint = Joint(parent, child, joint_type, parent_cg_to_joint, joint_to_child_cg, prismatic_direction)
        self.joints.append(joint)

    @classmethod
    def from_data(cls, joints, types, parent_cg_to_joint, joint_to_child_cg, prismatic_direction):
        """
        Build a JointSystem from arrays/lists corresponding to MATLAB inputs.
        """
        system = cls()
        for i, (parent, child) in enumerate(joints):
            system.add_joint(parent,
                             child,
                             types[i],
                             parent_cg_to_joint[i],
                             joint_to_child_cg[i],
                             prismatic_direction[i])
         
        system.joints = sorted(system.joints,key=lambda joint: joint.child)
        return system

    def display_table(self):
        """Displays the joint system in a table format."""
        def format_vector(vec):
            """Formats vector elements to 3 decimal places if they are numbers."""
            if vec is None or vec.has(sym.nan):
                return "NaN  NaN"
            if isinstance(vec, sym.Matrix):
                vec = vec.tolist()
                # Flatten if it's a column vector (e.g. [[x1], [x2]])
                if len(vec) > 0 and isinstance(vec[0], list):
                    vec = [v[0] for v in vec]
            if isinstance(vec, (int, float)):
                return f"{vec:.2f}"
            # elif isinstance(vec, sym.Basic):  # catches Symbol, Expr, MatrixElement, etc.
            #     return str(vec)
            else:
                return str(vec)

        data = {
            "Joint": list(range(1, len(self.joints) + 1)),  # Numbering joints sequentially
            "Connected Bodies": [f"{joint.parent} {joint.child}" for joint in self.joints],
            "Joint Type": [joint.joint_type.value for joint in self.joints],
            "ParentCGtoJoint": [format_vector(joint.parent_cg_to_joint) for joint in self.joints],
            "JointtoChildCG": [format_vector(joint.joint_to_child_cg) for joint in self.joints],
            "Prismatic Direction": [format_vector(joint.prismatic_direction) for joint in self.joints]
        }

        df = DataFrame(data)
        from ..tables.points_forces_table import print_grid_table
        print_grid_table(df)


    def coordinate_finder(self):
        """
        Associates each joint with its corresponding symbolic coordinate variables for positions (Q),
        velocities (QD), and accelerations (QDD), based on the joint type. The joints are sorted
        by their child body number so that the DOF labeling index (used in the symbolic variable names)
        matches the child-body number.

        Joint types:
            - 'R' (Revolute): 1 DOF (rotational).
            - 'P' (Prismatic): 1 DOF (translational).
            - 'F' (Floating in 2D): 3 DOFs (X, Z, Theta).

        Returns:
            Q (list): List of symbolic variables for joint positions.
            QD (list): List of symbolic variables for joint velocities.
            QDD (list): List of symbolic variables for joint accelerations.
            DOF_list (list): List containing the DOF count for each joint.
            Body_col (list of lists): Each sublist contains the global DOF indices for the corresponding joint.
        """
        # import sympy as sp  # Using SymPy for symbolic mathematics.

        Q   = []        # Global list of position variables
        QD  = []        # Global list of velocity variables
        QDD = []        # Global list of acceleration variables
        DOF_list = []   # List of DOF per joint

        # Start Body_col with an initial dummy list containing 0
        Body_col = [[-1]]

        # For each joint in the sorted order, use the joint.child value as the label index.
        for joint in self.joints:
            label = joint.child  # Use the child-body number as the index in the symbolic names

            if joint.joint_type.value == 'R':
                # Revolute joint: one rotational DOF.
                q   = sym.symbols(f'Theta_{label}', real=True)
                qd  = sym.symbols(f'ThetaD_{label}', real=True)
                qdd = sym.symbols(f'ThetaDD_{label}', real=True)
                dof = 1

            elif joint.joint_type.value == 'P':
                # Prismatic joint: one translational DOF.
                q   = sym.symbols(f'S_{label}', real=True)
                qd  = sym.symbols(f'SD_{label}', real=True)
                qdd = sym.symbols(f'SDD_{label}', real=True)
                dof = 1
                
            elif joint.joint_type.value == 'F':
                # Floating joint in 2D: three DOFs (X, Z, Theta).
                q   = [sym.symbols(f'X_{label}', real=True),
                       sym.symbols(f'Z_{label}', real=True),
                       sym.symbols(f'Theta_{label}', real=True)]
                qd  = [sym.symbols(f'XD_{label}', real=True),
                       sym.symbols(f'ZD_{label}', real=True),
                       sym.symbols(f'ThetaD_{label}', real=True)]
                qdd = [sym.symbols(f'XDD_{label}', real=True),
                       sym.symbols(f'ZDD_{label}', real=True),
                       sym.symbols(f'ThetaDD_{label}', real=True)]
                dof = 3
            else:
                raise ValueError(f"Joint type '{joint.joint_type.value}' is not defined. Check joint definition.")

            # Append the symbolic variables to the overall lists.
            if isinstance(q, list):
                Q.extend(q)
                QD.extend(qd)
                QDD.extend(qdd)
            else:
                Q.append(q)
                QD.append(qd)
                QDD.append(qdd)

            DOF_list.append(dof)

            # Update Body_col: compute new global indices for this joint's DOF.
            last_index  = Body_col[-1][-1]
            new_indices = list(range(last_index + 1, last_index + dof + 1))
            Body_col.append(new_indices)

        # Remove the initial dummy element.
        Body_col = Body_col[1:]

        return Q, QD, QDD, DOF_list, Body_col

